version: "3"
services:
  zookeeper:
    image: 'zookeeper'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'confluentinc/cp-kafka'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=172.17.0.3:2181 
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://172.17.0.3:9092 
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1 
    depends_on:
      - zookeeper